package bitmanipulation.leetcode

//problem : Find the Difference 389
/*
* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"*/
class SolutionFindTheDifference {
    fun findTheDifference(s: String, t: String): Char {
        var resXor = 0
        for (charIndex in s.indices) {
            resXor = resXor xor s[charIndex].toInt() xor t[charIndex].toInt()
        }
        return (resXor xor t[t.lastIndex].toInt()).toChar()
    }
}

fun main() {
    val ch = SolutionFindTheDifference().findTheDifference("abcd", "abcdf")
    println(ch)
}